# Generated by Django 6.0.1 on 2026-01-12 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Session identifier for anonymous users', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('context_metadata', models.JSONField(default=dict, help_text='Stores conversation context, extracted entities, etc.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Stores extracted entities, confidence scores, intent classification, etc.')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('symptom', 'Symptom Description'), ('prescription', 'Prescription Upload'), ('direct', 'Direct Medicine Search')], max_length=20)),
                ('medicine_names', models.JSONField(default=list, help_text='List of medicine names requested')),
                ('symptoms', models.TextField(blank=True, help_text="Symptom description if request_type is 'symptom'")),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=500)),
                ('location_suburb', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('broadcasting', 'Broadcasting'), ('awaiting_responses', 'Awaiting Responses'), ('responses_received', 'Responses Received'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to='chatbot.chatconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyResponse',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacy_id', models.CharField(max_length=255)),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('medicine_available', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preparation_time', models.IntegerField(default=0, help_text='Time in minutes to prepare medicine')),
                ('distance_km', models.FloatField(blank=True, help_text='Distance from patient location', null=True)),
                ('estimated_travel_time', models.IntegerField(blank=True, help_text='Estimated travel time in minutes', null=True)),
                ('alternative_medicines', models.JSONField(default=list, help_text='List of alternative medicines suggested')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_responses', to='chatbot.medicinerequest')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
    ]
