# Generated by Django 6.0.1 on 2026-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_pharmacy_remove_pharmacyresponse_pharmacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyresponse',
            name='medicine_responses',
            field=models.JSONField(blank=True, default=list, help_text='Per-medicine availability, prices, and alternatives'),
        ),
        migrations.AlterField(
            model_name='pharmacyresponse',
            name='alternative_medicines',
            field=models.JSONField(default=list, help_text='List of alternative medicines suggested (legacy - use medicine_responses)'),
        ),
    ]
