# Generated by Django 6.0.1 on 2026-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_add_medicine_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='rating',
            field=models.FloatField(blank=True, default=0, help_text='Average rating 0-5'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rating_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of ratings received'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='response_rate',
            field=models.FloatField(blank=True, default=100, help_text='Response rate percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('broadcasting', 'Broadcasting'), ('awaiting_responses', 'Awaiting Responses'), ('partial', 'Partial'), ('timeout', 'Timeout'), ('responses_received', 'Responses Received'), ('ranking', 'Ranking'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=20),
        ),
    ]
