# Generated by Django 6.0.1 on 2026-03-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_add_pharmacy_rating_response_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyresponse',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Medicine expiry date', null=True),
        ),
        migrations.AddField(
            model_name='pharmacyresponse',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Total quantity (e.g. capsules)', null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyresponse',
            name='medicine_responses',
            field=models.JSONField(blank=True, default=list, help_text='Per-medicine availability, prices, quantity, expiry, alternatives'),
        ),
        migrations.CreateModel(
            name='PharmacistDecline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declined_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_requests', to='chatbot.pharmacist')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_declines', to='chatbot.medicinerequest')),
            ],
            options={
                'ordering': ['-declined_at'],
                'unique_together': {('request', 'pharmacist')},
            },
        ),
    ]
