# Generated by Django 6.0.1 on 2026-03-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_add_pharmacy_dashboard_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0, help_text='Units in stock')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert when quantity drops below this')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='chatbot.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'Pharmacy inventory',
                'ordering': ['medicine_name'],
                'unique_together': {('pharmacy', 'medicine_name')},
            },
        ),
    ]
