# Generated by Django 6.0.1 on 2026-03-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_add_pharmacy_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 stars')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='chatbot.pharmacy')),
                ('response', models.ForeignKey(blank=True, help_text='Optional: link to the response/visit being rated', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.pharmacyresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
