# Generated by Django 6.0.1 on 2026-03-03 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_add_pharmacy_rating_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinventory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit for ranking', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Quantity reserved by patients (locks stock)'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, help_text='For anonymous reservations', max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=50)),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_reservation', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of reservation', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Reservation expires 2 hours after creation')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='chatbot.chatconversation')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='chatbot.pharmacy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
    ]
