# Generated by Django 6.0.1 on 2026-03-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_add_reservation_and_inventory_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('home_area', models.CharField(blank=True, help_text='e.g. Avondale, Harare', max_length=200)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('allergies', models.JSONField(default=list, help_text="e.g. ['Penicillin']")),
                ('conditions', models.JSONField(default=list, help_text="e.g. ['Type 2 Diabetes', 'Hypertension']")),
                ('max_search_radius_km', models.IntegerField(blank=True, default=10, null=True)),
                ('sort_results_by', models.CharField(choices=[('best_match', 'Best Match (AI)'), ('nearest', 'Nearest First'), ('cheapest', 'Cheapest First')], default='best_match', max_length=30)),
                ('notify_pharmacy_responses', models.BooleanField(default=True)),
                ('notify_request_expiry', models.BooleanField(default=True)),
                ('notify_drug_interactions', models.BooleanField(default=True)),
                ('notify_medibot_followup', models.BooleanField(default=False)),
                ('notification_method', models.CharField(default='in_app', max_length=20)),
                ('share_location_with_pharmacies', models.BooleanField(default=True)),
                ('save_search_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('medicine_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='e.g. Paracetamol 500mg', max_length=255)),
                ('last_searched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session_id', 'medicine_name')},
            },
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('notification_type', models.CharField(choices=[('pharmacy_response', 'Pharmacy Response'), ('drug_alert', 'Drug Interaction Alert'), ('request_fulfilled', 'Request Fulfilled'), ('request_expired', 'Request Expired'), ('medibot_followup', 'MediBot Follow-up'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('related_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_response_id', models.UUIDField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
