# Generated by Django 6.0.1 on 2026-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_patient_dashboard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
