# Generated by Django migration — pharmacy registry fields + AdminAuditLog

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0010_reservation_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_type',
            field=models.CharField(blank=True, default='', help_text='e.g. retail, chain, hospital (admin registry)', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verification_status',
            field=models.CharField(
                choices=[('verified', 'Verified'), ('pending_review', 'Pending review'), ('suspended', 'Suspended')],
                default='verified',
                help_text='Registry verification pill; inactive pharmacies still show as suspended in API.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='last_inventory_sync_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Optional official inventory sync timestamp (otherwise max inventory.updated_at is used).',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
