# Generated by Django 6.0.1 on 2026-03-31 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_medicine_request_ranking_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequestRankingSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(db_index=True, help_text='ranked_api | patient_portal', max_length=32)),
                ('limit_applied', models.PositiveSmallIntegerField(default=0)),
                ('ranked_items', models.JSONField(default=list, help_text='Ordered list as returned to the client (rank, scores, pharmacy ids, flags).')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to='chatbot.medicinerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', '-created_at'], name='chatbot_med_request_251425_idx')],
            },
        ),
    ]
