# Generated by Django 6.0.1 on 2026-04-04 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_medicine_request_ranking_snapshot_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdminSettings',
            fields=[
                ('singleton_id', models.CharField(default='main', max_length=16, primary_key=True, serialize=False)),
                ('active_ranking_profile', models.CharField(blank=True, default='', help_text='urban_default | rural_equity | shortage_mode | custom', max_length=64)),
                ('ranking_weights_urban', models.JSONField(blank=True, default=dict)),
                ('ranking_weights_rural', models.JSONField(blank=True, default=dict)),
                ('chatbot_policy', models.JSONField(blank=True, default=dict)),
                ('reported_uptime_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual uptime %% for dashboard when not instrumented.', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Platform admin settings',
            },
        ),
        migrations.AlterField(
            model_name='medicinerequestrankingsnapshot',
            name='source',
            field=models.CharField(db_index=True, help_text='ranked_api | patient_portal | chat_assistant', max_length=32),
        ),
        migrations.CreateModel(
            name='ChatbotSafetyReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('safe', 'Safe')], db_index=True, default='warning', max_length=16)),
                ('patient_query', models.TextField(blank=True)),
                ('bot_response', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reviews', to='chatbot.chatconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reviews', to='chatbot.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
