# Generated by Django 6.0.1 on 2026-04-08 14:17

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_medicinerequest_status_superseded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('geo_region', models.CharField(blank=True, max_length=120)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='Africa/Harare', max_length=64)),
                ('holiday_mode', models.BooleanField(default=False)),
                ('auto_accept_reservations', models.BooleanField(default=False)),
                ('max_reservation_window_minutes', models.PositiveIntegerField(default=120)),
                ('low_stock_threshold_default', models.PositiveIntegerField(default=5)),
                ('out_of_stock_behavior', models.CharField(choices=[('hide', 'Hide item'), ('allow_backorder', 'Allow backorder'), ('notify_only', 'Notify only')], default='hide', max_length=32)),
                ('auto_substitute_enabled', models.BooleanField(default=False)),
                ('notify_new_request', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_reservation_expiry', models.BooleanField(default=True)),
                ('notify_channel_sms', models.BooleanField(default=False)),
                ('notify_channel_email', models.BooleanField(default=True)),
                ('notify_channel_in_app', models.BooleanField(default=True)),
                ('preferred_profile', models.CharField(blank=True, max_length=64)),
                ('disclaimer_visible', models.BooleanField(default=True)),
                ('prescription_enforcement', models.BooleanField(default=False)),
                ('audit_logging_enabled', models.BooleanField(default=True)),
                ('ui_dark_mode', models.BooleanField(default=False)),
                ('ui_table_density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=16)),
                ('ui_default_page_size', models.PositiveIntegerField(default=25)),
                ('ui_default_filters', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySettingsHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_by', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(default='patch', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to='chatbot.pharmacist'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='pharmacy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='chatbot.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacysettingshistory',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='chatbot.pharmacysettings'),
        ),
    ]
